<div class="value external-js-value">
    <div class="input-body">
        <input type="text" name="external-js[<?php echo $externalJsFieldCount; ?>]" aria-labelledby="external-js-label" value="<?php echo $externalJsValue; ?>" data-field-count="<?php echo $externalJsFieldCount; ?>">
    </div>
    <div class="input-footer">
        <ul class="actions">
            <li><a class="o-icon-delete remove-value" title="Remove value" href="#" aria-label="Remove value"></a></li>
        </ul>
    </div>
</div>